version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=interview
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./create_table.sql:/docker-entrypoint-initdb.d/create_table.sql

  api:
    build:
       context: .
       dockerfile: Dockerfile
    ports:
      - '80:80'
    container_name: backend-interview-services
    depends_on:
     - db
    environment:
      - APP_HOST=0.0.0.0
      - APP_PORT=80
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=interview
      - DB_TYPE=postgres


  
     
volumes:
 postgres-data:
